application:
  title: OpenCFP
  url: http://192.168.33.77/
  email: mance2012@gmail.com
  eventurl: http://192.168.33.77/
  enddate: Oct. 14th, 2016
  show_submission_count: false
  airport: MIA
  arrival: 2014-10-26
  departure: 2014-10-31
  secure_ssl: false

api:
  enabled: true

cache:
  enabled: false

database:
  host: localhost
  database: cfp_travis
  dsn: mysql:dbname=cfp_travis;host=localhost
  user: root
  password: '123456'

mail:
  host: ~
  port: ~
  username: ~
  password: ~
  encryption: ~
  auth_mode: ~
